name: Rust release

permissions:
  contents: write
  
on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:    
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            extension: ""
            runner: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            extension: ""
            runner: ubuntu-24.04-arm
          - target: x86_64-pc-windows-msvc
            extension: ".exe"
            runner: windows-latest
          - target: aarch64-pc-windows-msvc
            extension: ".exe"
            runner: windows-11-arm
          - target: aarch64-apple-darwin
            extension: ""
            runner: macos-latest
          
    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v4
    - name: Add target
      run: rustup target add ${{ matrix.target }}
    - name: Build
      run: cargo build --release --package caretta-id-cli --target ${{ matrix.target }} --verbose 
    - name: Rename Artifacts
      shell: bash
      run: mv target/${{ matrix.target }}/release/caretta-id-cli{,-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.extension }}}
    - name: Uploard Artifacts
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        files: target/${{ matrix.target }}/release/caretta-id-cli-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.extension }}
